baseURL = 'https://blog.blackpiratex.com/'
languageCode = 'en-us'
title = 'Blog By BlackPirateX'
theme = 'newcss'


[params]
  author = 'BlackPirateX'
  description = "A place for me to write down my thoughts, rants, and reviews."
  tags = 'tags'
  catagories = 'catagories'
[imaging]
  anchor = 'Smart'
  quality = 25
  resampleFilter = 'Box'